describe('All tests spec', () => {
  it('Should check all tests page', () => {
    cy.visit('/tests')
    cy.get('.c-text--text-xl').should('contain', 'All Tests Kinds')
    cy.get('.recharts-surface')
    cy.get('div>ul>li>span').should('have.attr', 'color')
    cy.get('.c-text--text-xl').should('contain', 'All Tests Status')
    cy.get('.c-native-link ').should('have.value', '').eq(0).click()
    cy.get('.o-center-layout')
    cy.get('[data-element="button"').contains('Cancel').click()
    cy.get('input').type('?Working?')
    cy.get('.c-native-link ').should('not.exist')
    cy.get('input').clear()
    cy.get('td>.c-text--text-s').should('have.value', '')
    cy.get('td>div>.c-text--text-s').should('have.value', '')
    cy.get('td>[data-element="button"]').should('have.value', '')
    cy.get('nav>ul>li>a').eq(1).click()
    cy.get('[data-element="dropdown"]>div>div>span').eq(0).click()
    //how to select from dropdown here ??
    cy.get('[data-element="dropdown"]>div>div>span').eq(1).click()
    cy.get('[data-element="button"]').contains('All Behaviours').click()
    cy.url().should('eq', Cypress.config().baseUrl + '/behaviors')
    cy.get('h5.c-text--heading-5').should('contain', 'Systems').click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
})
