describe('Homepage spec', () => {
  it('Should check homepage', () => {
    cy.homepage()
    cy.get('h5.c-text--heading-5').should('contain', 'Systems')
    cy.get('tbody>tr>td>div>span>a').eq(0).should('have.value', '')
    cy.get('tbody>tr>td>div>span').eq(1).should('have.value', '')
    cy.get('tbody>tr>td>div>div').eq(0).trigger('mouseenter')
    cy.get('.__react_component_tooltip').children().should('contain', '%')
    cy.get('tbody>tr>td>div>div').eq(0).click()
    cy.visit('/')
    cy.get('tbody>tr>td>div>div').eq(1).trigger('mouseenter')
    cy.get('.__react_component_tooltip').children().should('contain', '%')
    cy.get('tbody>tr>td>div>span>a').eq(1).click()
    cy.visit('/')
    cy.get('[data-element="button"]>span').contains('All Tests').click()
    cy.url().should('eq', Cypress.config().baseUrl + '/tests')
    cy.get('div>a').contains('System Test Matrix').click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
    cy.get('[data-element="button"]>span').contains('All Behaviours').click()
    cy.get('h5.c-text--heading-5').should('contain', 'Systems').click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
    cy.get('tbody>tr>td>button>span').should('have.value', '')
  })
})
