describe('Subsystem specs', () => {
  it('Should check subsystem page', () => {
    cy.visit('/')
    cy.get('tbody>tr>td>div>span>a').eq(0).click()
    cy.get('tbody>tr>td>span>a').eq(0).click()
    cy.get('[data-element="button"]>span').should('have.value', '')
    cy.get('.c-text--text-xl').contains('All Tests Kinds')
    cy.get('.c-text--text-xl').contains('All Behaviors Status')
    cy.get('div>ul>li>span').should('have.attr', 'color')
    cy.get('.recharts-responsive-container')
    cy.viewport(768, 1024)
    cy.get('.c-page-layout__section')
      .eq(1)
      .children()
      .children()
      .first()
      .scrollTo('right')
      .scrollTo('left')
    cy.viewport(Cypress.config().viewportWidth, Cypress.config().viewportHeight)
    cy.get('div')
      .contains('Untested behavior ')
      .children()
      .first()
      .should('have.css', 'background')
    cy.get('div')
      .contains('Tested behavior ')
      .children()
      .first()
      .should('have.css', 'background')
    cy.get('h5.c-text--heading-5')
      .should('contain', 'Systems')
      .parents()
      .next()
      .next()
      .children()
      .first()
      .click()
    cy.get('h5.c-text--heading-5').should('contain', 'Systems').click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
})
