describe('System specs', () => {
  it('Should check system page', () => {
    cy.visit('/')
    cy.get('tbody>tr>td>div>span>a').eq(0).click()
    cy.get('.recharts-surface')
    cy.get('[data-element="button"]>span').should('have.value', '')
    cy.get('div>ul>li>span').should('have.attr', 'color')
    cy.get('.c-text--text-xl').contains('All Tests Kinds')
    cy.get('.c-text--text-xl').contains('All Behaviors Status')
    cy.get('.recharts-responsive-container')
    cy.get('input').type('?Working?')
    cy.get('.c-native-link ').should('not.exist')
    cy.get('input').clear()
    cy.get('.c-native-link ')
    cy.get('[data-element="dropdown"]>div>div>span').eq(0).click()
    cy.get('[data-element="dropdown"]>div>div>span').eq(1).click()
    cy.get('div>span').contains('Detailed view').click()
    cy.viewport(768, 1024)
    cy.get('.c-page-layout__section>div>div')
      .next()
      .children()
      .first()
      .scrollTo('right')
      .scrollTo('left')
    cy.viewport(Cypress.config().viewportWidth, Cypress.config().viewportHeight)
    cy.get('div')
      .contains('Untested behavior ')
      .children()
      .first()
      .should('have.css', 'background')
    cy.get('div')
      .contains('Tested behavior ')
      .children()
      .first()
      .should('have.css', 'background')
    cy.get('div>span').contains('Overview').click()
    cy.get('h5.c-text--heading-5').should('contain', 'Systems').click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
})
