@startuml ER

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity TestSuite {
  * path: string
  --
  * kind: enum(string)
  * status: enum(string)
}


entity System {
  * name: string
  --
  description: string
}

entity Subsystem {
  * name: string
  --
  description: string
}

entity Feature {
  * name: string
  --
  description: string
}

entity Scenario {
  * id: string
  --
  * description: string
}

entity Repository {
  * url: string
  --
  description: string
}

entity Package {
  * name: string
  --
  description: string
}

System ||--|{ Subsystem
Subsystem ||--|{ Feature
Feature ||--|{ Scenario
Scenario }|-right-o{ TestSuite
TestSuite }o-up-|| Package
Package }|-up-|| Repository

@enduml