
@startuml ER

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity Feature {
  * id: string
  --
  * name: string
}

entity Scenario {
  * id: string
  --
  * description: string
}

entity TestSuite {
  * path: string
  --
  * kind: enum(string)
  * status: enum(string)
}

entity TestCase {
  * name: string
  --
  status: enum("pass", "fail")
}

entity Subsystem {
  * name: string
  --
  description: string
}

entity Repository {
  * url: string
  --
  description: string
}

entity Package {
  * name: string
  --
  description: string
}

Subsystem ||-down-|{ Feature
TestSuite }o-up-|| Package
Package }|-up-|| Repository
Scenario }|-up-|| Feature
TestCase }|-left-|| TestSuite
TestCase }|-right-|{ Scenario

@enduml