#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

SRC_PATTERN="frontend/"

if git diff @{push} --cached --name-only | grep --quiet "$SRC_PATTERN"
then
  cd frontend || exit
  yarn format
  yarn lint
  yarn commitlint --edit $1
else
  exit 0
fi


