name: Deploy Test Crawler
on: [push]
jobs:
  run-test-crawler:
    runs-on: ubuntu-latest
    steps:
      # Clone lotus repo
      - uses: actions/checkout@v2
        with:
          repository: filecoin-project/lotus
          path: test-crawler

      # Install go lang
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.7"

      # Install build-essential
      - name: install build-essential
        run: sudo apt-get install build-essential

      # run test crawler
      - name: make build
        working-directory: ./test-crawler
        run: make run

      # copy crawler output
      - name: copy output
        working-directory: ./test-crawler
        run: make copy-output
