name: Deploy Test Crawler
on: [push]
jobs:
  run-test-crawler:
    runs-on: ubuntu-latest
    steps:
      # Clone lotus repo
      - name: Clone lotus  repo
        uses: actions/checkout@v2
        with:
          repository: filecoin-project/lotus
          path: repo-to-crawl

      # Install go lang
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.7"

      # Install build-essential
      - name: Install build-essential
        run: sudo apt-get install build-essential

      # run test crawler
      - name: Make run
        run: pwd
        # working-directory: test-crawler

      # copy crawler output
      - name: Copy output
        run: pwd
        working-directory: test-crawler
